Repository bystrogenomics/bystro, pull requests merged in 2023-09, with the labels that each got.

#240 Gaussian Factor Analysis Models
  python/python/bystro/supervised_ppca/_base.py
  python/python/bystro/supervised_ppca/_misc_np.py
  python/python/bystro/supervised_ppca/gf_generative_pt.py
  python/python/bystro/supervised_ppca/ppca_analytic_np.py
  python/python/bystro/supervised_ppca/tests/test_generative_pt.py
Labels: ml

#242 Add proteomics upload CLI
  python/python/bystro/proteomics/proteomics_cli.py
  python/python/bystro/proteomics/tests/experiment_annotation_file.tsv
  python/python/bystro/proteomics/tests/protein_abundance_file.tsv
  python/python/bystro/proteomics/tests/test_proteomics_cli.py
Labels: proteomics

#264 Make sure ray starts with serve-dev
  Makefile
Labels: bug

#255 Feature/dropout ppca
  python/python/bystro/supervised_ppca/gf_dropout_pt.py
  python/python/bystro/supervised_ppca/gf_generative_pt.py
  python/python/bystro/supervised_ppca/tests/test_dropout_pt.py
  python/python/bystro/supervised_ppca/tests/test_generative_pt.py
Labels: ml
